name: users_calendar_view

version: 0.0.2

description: Collection of customisable calendar related widgets for Flutter.

author: ZedTheLed<zedtheled@gmail.com>

homepage: https://github.com/ZedTheLed/calendar_views

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.26.0-17.2.pre"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.2.4
  quiver: ^2.1.5
