name: users_calendar_view

version: 1.0.0

description: Collection of customisable calendar related widgets for Flutter.

author: ZedTheLed<zedtheled@gmail.com>

homepage: https://github.com/ZedTheLed/calendar_views

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.26.0-17.2.pre"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.3.0
  quiver: ^3.0.1
